### ISSUE TITLE
Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by tobias-vdp** [hjdhjd/homebridge-unifi-protect2#12]
after installation i received the following error (udm pro, protect active, 2 cameras installed)

(node:23172) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at requestPromise.get.then.response (/usr/local/lib/node_modules/homebridge-unifi-protect2/index.js:118:32)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-unifi-protect2/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:23172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Veldkornet** [comment]
I have the same problem on my UDM-Pro

![BFB80D49-7A9C-4B11-87A9-EE983F6EA60E](https://user-images.githubusercontent.com/10297361/74968436-2207ad00-541b-11ea-8f35-ede4be17d879.jpeg)

**Comment by jonbloom** [comment]
Try my version here: https://github.com/jonbloom/homebridge-unifi-protect2. It supports the UDM Pro. 

It appears this repo is abandoned? I made a PR but have heard nothing back.

**Comment by Veldkornet** [comment]
Yup, already using it :)

**Comment by tobias-vdp** [comment]
hmm, not sure - if i run sudo npm install -g homebridge-unifi-protect2 - i seem to be unable to install your version - it always installs the abandoned one - any idea?

**Comment by jonbloom** [comment]
@tobias-vdp @Veldkornet I have published my own version since this repo seems to be unmaintained:

https://github.com/jonbloom/homebridge-ufp

**Comment by hjdhjd** [comment]
Sorry guys this isn’t abandoned. It’s been a long 3 months. I’ll incorporate the updates in the coming week.
