### ISSUE TITLE
I added new camera to Protect and got these errors, had to restart the plugin to get the new camera recognized by the plugin / added to HOME.

### ISSUE THREAD

**Issue by fpuigb** [hjdhjd/homebridge-unifi-protect2#37]
**Plugin  (homebridge-unifi-protect2 v3.1.3)**

(node:16903) UnhandledPromiseRejectionWarning: Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:230:29)
    at new PlatformAccessory (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:69:9)
    at ProtectNvr.discoverAndSyncAccessories (/usr/lib/node_modules/homebridge-unifi-protect2/src/protect-nvr.ts:120:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at ProtectNvr.updateAccessories (/usr/lib/node_modules/homebridge-unifi-protect2/src/protect-nvr.ts:203:5)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-unifi-protect2/src/protect-nvr.ts:371:7)
(node:16903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by hjdhjd** [comment]
Appreciate you catching this edge case. I’ll push an update to address this. The error is related to the fact that the plugin is trying to pull the name before the Protect controller has had a chance to populate it.

**Comment by hjdhjd** [comment]
Fixed in v3.2.0. Thanks for catching this one.
