### ISSUE TITLE
problems after updating 3.6.0

### ISSUE THREAD

**Issue by henkied** [hjdhjd/homebridge-unifi-protect2#63]
After updating to version 3.6.0 I get the error below. I reinstalled everything (pluging is installed!!) but unfortunately no results. Hombridge version is current:

Error: The requested platform 'UniFi Protect' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by hjdhjd** [comment]
This looks like an npm upgrade error. Please completely uninstall the plugin:

`npm -g uninstall homebridge-unifi-protect2` and then reinstall it:
`npm -g install homebridge-unifi-protect2` and see if that does the trick.

**Comment by hjdhjd** [comment]
Fixed in v3.6.1.
