### ISSUE TITLE
Upgrade to 3.6.0 Unsuccessful 

### ISSUE THREAD

**Issue by fpuigb** [hjdhjd/homebridge-unifi-protect2#64]
After upgraded to 3.6.0 in a Ubuntu 16.0.4 LTS VM I'm getting these errors. 

[9/4/2020, 7:23:04 AM] [Config] Initializing config platform...
[9/4/2020, 7:23:04 AM] [Config] Running in Service Mode
[9/4/2020, 7:23:04 AM] Error loading platform requested in your config.json at position 2
[9/4/2020, 7:23:04 AM] Error: The requested platform 'UniFi Protect' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
[9/4/2020, 7:23:04 AM] Got SIGTERM, shutting down Homebridge...
[9/4/2020, 7:23:09 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by shard87** [comment]
+ 1, had to roll back to 3.5.1
npm -g uninstall homebridge-unifi-protect2
npm -g install homebridge-unifi-protect2@3.5.1

**Comment by miwagner1** [comment]
Same issue here as well

**Comment by raneses-sg** [comment]
Same on my end, running the plugin in the latest version of Hoobs. Startup log:

```
9/4/2020, 5:54:11 AM Error loading plugin "homebridge-unifi-protect2".
9/4/2020, 5:54:11 AM /hoobs/node_modules/homebridge-unifi-protect2/dist/protect-platform.js:27
            ffmpegOptions: config.ffmpegOptions ?? settings_1.PROTECT_FFMPEG_OPTIONS,
                                                 ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/hoobs/node_modules/homebridge-unifi-protect2/dist/index.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

**Comment by hjdhjd** [comment]
@raneses-sg HOOBS may not be on the latest version of Homebridge. It’s not officially supported. As stated in the Changelog, this version **requires** Homebridge 1.1.3 or greater.

**Comment by hjdhjd** [comment]
@fpuigb Can you uninstall the plugin completely and reinstall cleanly and see if that works? Thanks.

**Comment by miwagner1** [comment]
Same issue with Homebridge installed on Raspberry Pi OS. Fresh reinstall and reconfigure. same errors

**Comment by coomacheek** [comment]
Same issue.  I'm on 1.1.3 as well.

**Comment by hjdhjd** [comment]
Would you mind trying completely uninstall both homebridge and the plugins, and reinstalling?

**Comment by coomacheek** [comment]
Uninstalled and unchecked the "Remove Plugin Config"  -- Same problem
Uninstalled and checked the "Remove Plugin Config" -- Same problem

**Comment by hjdhjd** [comment]
Alright...let me ask this: what version of node are you guys on?

3.6.0 leverages a lot of modern features in node 14 and beyond.

**Comment by miwagner1** [comment]
v12.18.3... ahhhhh

**Comment by hjdhjd** [comment]
Well...upgrade and give it a whirl. :smile:

**Comment by miwagner1** [comment]
will do, the guide on https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian uses v12

**Comment by erictaylor** [comment]
Can confirm issues.
Node LTS is still v12.18.3. Just FYI v14 doesn't go LTS until end of October.

**Comment by miwagner1** [comment]
upgrading to v14 fixed the issue.

**Comment by hjdhjd** [comment]
Alright all - I've tracked this down I think. I'll push an update shortly to increase compatibility with node 12. That should fix things...give me a bit to move some things around and push an update.

**Comment by hjdhjd** [comment]
Please try v3.6.1. Thanks!

**Comment by zakdeutsch** [comment]
Back in action here w/ v3.6.1.  Thanks for the quick fix!

**Comment by erictaylor** [comment]
For clarification @hjdhjd, is it still expected that if you have a Doorbell to still disable two way audio? Or should that be working now?

**Comment by hjdhjd** [comment]
Great. Closing.

**Comment by hjdhjd** [comment]
@erictaylor Please open a new issue if you have one.

**Comment by raneses-sg** [comment]
@hjdhjd Appreciate the timely fix, deployed Homebridge proper and verified as working. No go with the latest version of Hoobs without a Node upgrade.

**Comment by hjdhjd** [comment]
HOOBS will also need to run homebridge 1.1.3 or better as well. Good luck.
